image: node:12

variables:
  NODE_ENV: test

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

stages:
  - lint
  - test
  - build

before_script:
  - yarn

lint-js:
  stage: lint
  script: yarn test:lint:js

lint-sass:
  stage: lint
  script: yarn test:lint:sass

jest:
  stage: test
  script: yarn test:jest

build-development:
  stage: build
  script: yarn build:development
  variables:
    NODE_ENV: development
  artifacts:
    paths:
    - public

build-production:
  stage: build
  script: yarn build:production
  variables:
    NODE_ENV: production
  artifacts:
    paths:
    - public

i18n:
  stage: build
  script: yarn manage:translations
  before_script:
    - yarn
    - yarn build:development
