image: node:12

variables:
  NODE_ENV: test

stages:
  - lint
  - build
  - test

before_script:
  - yarn

lint-js:
  stage: lint
  script: yarn test:lint:js

lint-sass:
  stage: lint
  script: yarn test:lint:sass

i18n:
  stage: lint
  script: yarn manage:translations

build-development:
  stage: build
  script: yarn build:development
  variables:
    NODE_ENV: development
  artifacts:
    paths:
    - public/packs

build-production:
  stage: build
  script: yarn build:production
  variables:
    NODE_ENV: production
  artifacts:
    paths:
    - public/packs

jest:
  stage: test
  script: yarn test:jest
