cobalt: styles/cobalt.scss
purple: styles/gabsocial-light.scss
purple-dark: styles/application.scss
purple-contrast: styles/contrast.scss
halloween: styles/halloween.scss
aquatic: styles/neenster.scss
paleblue: styles/glinner.scss
lime: styles/lime.scss
